package com.openclassrooms.magicgithub.api

import com.openclassrooms.magicgithub.api.FakeApiServiceGenerator.FAKE_USERS
import com.openclassrooms.magicgithub.model.User

class FakeApiService : ApiService {
    private val _users = FAKE_USERS.toMutableList().apply {
        addAll(FakeApiServiceGenerator.FAKE_USERS) // Initialize with predefined users
    }

    /**
     * Return a list of [User]
     * Those users must be generated by [FakeApiServiceGenerator]
     */
    override fun getUsers(): List<User> {
        return _users.toList()
    }

    /**
     * Generate a random [User] and add it to the [_users] list.
     * This user must be retrieved from the [FakeApiServiceGenerator.FAKE_USERS_RANDOM] list.
     */
    override fun addRandomUser() {
        val randomUser = FakeApiServiceGenerator.FAKE_USERS_RANDOM.randomOrNull()
        randomUser?.let { _users.add(it) }
    }

    /**
     * Delete a [User] from the [_users] list.
     */
    override fun deleteUser(user: User) {
        _users.remove(user)
    }
}
